// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OK9DAfCmNgw00-wInS5WcNlFgrw3WSo',
    appId: '1:771428466779:web:659b780919165a24417f7e',
    messagingSenderId: '771428466779',
    projectId: 'fir-app-396e9',
    authDomain: 'fir-app-396e9.firebaseapp.com',
    databaseURL: 'https://fir-app-396e9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-396e9.appspot.com',
    measurementId: 'G-HV7QWQ9KDX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2OK9DAfCmNgw00-wInS5WcNlFgrw3WSo',
    appId: '1:771428466779:web:08c1d08dc34ee8f6417f7e',
    messagingSenderId: '771428466779',
    projectId: 'fir-app-396e9',
    authDomain: 'fir-app-396e9.firebaseapp.com',
    databaseURL: 'https://fir-app-396e9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-396e9.appspot.com',
    measurementId: 'G-ED18MCNLL1',
  );
}
